spring:
  datasource:
    url: jdbc:mysql://localhost:3306/samdi_db
    username: root
    password: qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update